  name: github
  repo: yourusername/aridcode-initiative
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "events"
    label: "Events & News"
    file: "events.json"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string"}
